name: dsgrid-emr
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3
  - pysftp
  - python>=3.6.0
  - sshtunnel
  - requests
  - pyyaml
  - s3fs
  - flit

  # - aiobotocore #==1.3.1
  # - aiohttp #==3.7.4.post0
  # - aioitertools #==0.7.1
  # - async-timeout #==3.0.1
  # - attrs #==21.2.0
  # - bcrypt #==3.2.0
  # - boto3
  # - botocore #==1.20.49
  # - cffi #==1.14.5
  # - chardet #==4.0.0
  # - cryptography #==3.4.7
  # - fsspec #==2021.6.0
  # - gitdb #==4.0.7
  # - gitpython #==3.1.17
  # - idna #==3.2
  # - jmespath #==0.10.0
  # - multidict #==5.1.0
  # - paramiko #==2.7.2
  # - pycparser #==2.20
  # - pynacl #==1.4.0
  # - pysftp #==0.2.9
  # - python>=3.6.0
  # - python-dateutil #==2.8.1
  # - pyyaml #==5.4.1
  # - s3fs #==2021.6.0
  # - s3transfer #==0.3.7
  # - six #==1.16.0
  # - smmap #==4.0.0
  # - sshtunnel #==0.4.0
  # - typing-extensions #==3.10.0.0
  # - urllib3 #==1.26.5
  # - wrapt #==1.12.1
  # - yarl #==1.6.3
