name: Pytests

on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
        include:
          # Installing Spark on a Windows VM needs work.
          - os: ubuntu-latest
            python-version: "3.10"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install '.[admin]'
    - name: Run pytests
      run: |
        # This does not run the AWS tests.
        # Credentials would need to be configured.
        git submodule init
        git submodule update
        docker run -v $(pwd)/dsgrid-test-data:/dsgrid-test-data -p 8529:8529 -e ARANGO_ROOT_PASSWORD=openSesame -d --name arangodb-instance arangodb/arangodb:3.10.4
        docker exec arangodb-instance arangorestore --create-database --input-directory /dsgrid-test-data/filtered_registries/simple_standard_scenarios/dump --server.database simple-standard-scenarios --include-system-collections true --server.password openSesame --server.endpoint "http+tcp://localhost:8529"
        python -m pytest -v --disable-warnings --cov=./ --cov-report=xml:coverage.xml tests dsgrid/utils/py_expression_eval/tests.py
        docker kill arangodb-instance
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
